version: 2

models:
  - name: fact_sales
    description: "Fact table for aggregated sales"
    columns:
      - name: sale_date
        description: "Date of the sale"
        tests:
          - not_null
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - not_null
      - name: total_quantity
        description: "Total quantity sold"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue from sales"
        tests:
          - not_null

  - name: fact_customer_activity
    description: "Fact table for aggregated customer activity each date"
    columns:
      - name: user_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
      - name: activity_date
        description: "Date of the customer activity"
        tests:
          - not_null

  - name: dim_products
    description: "Dimension table for products"
    columns:
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Name of the product"
        tests:
          - not_null
      - name: category
        description: "Category of the product"
      - name: price
        description: "Price of the product"
        tests:
          - not_null